// Taken from https://github.com/asumansenol/double_edged_sword_crawler/blob/main/helpers/register_login_feature_extraction/register_login_vocabulary/login_action_vocabs.js
const loginActionVocabs = ['login',
    'log on',
    'sign in',
    'signin',
    'logon',
    'log-on',
    'sign-in',
    'log into',
    'sign-on',
    'sign on',
    'sign_in',
    'sign_on',
    'signon',
    'log in',
    'log_in',
    'log_on'];
