// Taken from https://github.com/asumansenol/double_edged_sword_crawler/blob/main/helpers/register_login_feature_extraction/register_login_vocabulary/newsletter_vocabs.js
const newsletterVocabs = ['newsletter',
    'ニュースレター',
    'النشرة الإخبارية',
    'bản tin',
    'จดหมายข่าว',
    'Surat berita',
    'न्यूज़लेटर',
    'নিউজলেটার',
    'bülten',
    'نیوز لیٹر',
    'email_list',
    'email list',
    'emaillist',
    'bulletin',
    'mail list',
    'email_list',
    'maillist',
    'mail_list',
    'subscribe',
    'subscrição',
    'subscrição',
    'mailinglist',
    'mailing_list',
    'mailing list'];
