// Taken from https://github.com/asumansenol/double_edged_sword_crawler/blob/main/helpers/register_login_feature_extraction/register_login_vocabulary/password_attr_vocabs.js
const passwordAttrVocabs = ['password',
    'pwd',
    'pass',
    'psw',
    'pssw',
    'passw',
    'pword',
    'passwd',
    'pswd',
    'psswd',
    'sehna',
    'clave',
    'motdepasse',
    'passwort',
    'contrasena'];
