// Taken from https://github.com/asumansenol/double_edged_sword_crawler/blob/main/helpers/register_login_feature_extraction/register_login_vocabulary/register_action_vocabs.js
const registerActionVocabs = ['\b(create).*?(account)\b',
    '\b(create).*?(user)\b',
    '\b(create).*?(profile)\b',
    '\b(reg).*?(user)\b',
    '\b(activate).*?(account)\b',
    '\b(free).*?(account)\b',
    'create_profile',
    'create_customer',
    'newuser',
    'new-reg',
    'new-form',
    'new_membership',
    'createaccount',
    'createAcct',
    'create-account',
    'reg-form',
    'signup',
    'register',
    'regform',
    'registration',
    'new_user',
    'accountcreate',
    'create-account',
    'sign/up',
    'membership',
    'membership/create',
    'new_account',
    'sign up',
    'sign-up',
    'sign_up',
    'account/create',
    'user/create'];
