// Taken from https://github.com/asumansenol/double_edged_sword_crawler/blob/main/helpers/register_login_feature_extraction/register_login_vocabulary/remember_me_action_vocabs.js
const rememberMeActionVocabs = ['remember',
    'manter',
    'mantenha',
    'savelogin',
    'auto login',
    'autologin',
    'auto_login',
    'auto-login',
    'save login',
    'save-login',
    'save_mail',
    'save-mail',
    'ricordami',
    'rememberme',
    'save id',
    'save-id',
    'save username',
    'save-username',
    'save email',
    'save-email'];
